[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'motemen/git-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/unite.vim.git'
