[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
# depends:
#  - set pyxversion=3
#  - pip3 install neovim
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'motemen/git-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/unite.vim.git'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

#NeoBundle 'datsuns/vim-smv'
#NeoBundle 'datsuns/vim-metarw-svn'
#NeoBundle 'datsuns/vim-metarw'
